version: "3"
services:
  # frontend:
  #   image: example/webapp
  #   ports:
  #     - "6000:6000"  
  node-backend:
    build: ./backend
    ports:
      - "3000:3000"  
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"