// User.js
const mongoose = require('mongoose');


/**
 * @swagger
 * components:
 *   schemas:
 *     Blog:
 *       type: object
 *       required:
 *         - author_id
 *         - title
 *         - body
 *       properties:
 *         _id:
 *           type: string
 *           description: Auto generated by the mongoDB (primary key)
 *         author_id:
 *           type: string
 *           description: ID of the author who created the blog post
 *         title:
 *           type: string
 *           description: Title of the blog post
 *         markdown_body:
 *           type: string
 *           description: Mardown code of the blog 
 *         tags:
 *           type: array
 *           items:
 *             type: string
 *           description: List of tags associated with the blog post
 *         thumbnailBase64:
 *           type: string
 *           description: Base64 encoded string of the blog's thumbnail image
 *         secondaryThumbnailBase64:
 *           type: string
 *           description: Base64 encoded string of the blog's secondary thumbnail image
 *         time:
 *           type: Date
 *           description: Base64 encoded string of the blog's thumbnail image
 *         status:
 *           type: array
 *           description: List of status updates for the blog
 *           items:
 *             type: object
 *             properties:
 *               message:
 *                 type: string
 *                 description: Status message of the blog
 *               time:
 *                 type: string
 *                 format: date-time
 *                 description: Timestamp when the status was updated* 
 */

const BlogSchema = new mongoose.Schema({
    authorId: { 
            type: String, 
            required: true
    },
    title: { 
            type: String, 
            required: true
    },
    markdown_body: { 
            type: String, 
            required: true 
    }, 
    tags : [
        { type: String, required: false }
    ], 
    thumbnailBase64: {
        type: String, 
        required: false 
    }, 
    secondaryThumbnailBase64: {
        type: String, 
        required: false 
    }, 
    status: [],
    time : {
        type: Date, 
        required: true 
    }, 
});

BlogSchema.methods.initializeAuthorId = function (authorId) {
    this.authorId = authorId; 
}

BlogSchema.methods.initializeTime = function () {
    this.time =  Date.now(); 
}

BlogSchema.methods.initializeStatus = function () {
    this.status.push({
        message: "Submitted", 
        time: Date.now()
    });
}

BlogSchema.methods.addNewStatus = function (name) {
    this.status.push({
        message: name, 
        time: Date.now()
    });
}

const Blog = mongoose.model('Blogs', BlogSchema);
module.exports = Blog;